// ============================================================
// Export Studio — Workbook Builder (DX-10, exceljs migration)
//
// Pure: ExportDataset -> ExcelJS.Workbook. Never writes a file itself
// (see exportDownloadService.ts) and never decides whether the
// workbook is safe to download (see exportValidation.ts) — those are
// separate steps in the pipeline by design.
//
// exceljs is dynamically imported rather than statically, so it lands
// in its own chunk instead of the main bundle every user downloads on
// first load — it's only needed on the admin-only Export Studio page.
// This makes buildExportWorkbook() async (it wasn't under the old
// SheetJS-CE writer); its only caller, exportDownloadService.ts, was
// already async for the same reason (buffer serialization).
// ============================================================
import type ExcelJS from 'exceljs'
import type { ExportDataset, ExportSheetData } from './exportTypes'
import { applySheetQuality, applyColumnFormat, formatForUnit } from './exportStyling'

const WORKBOOK_GENERATOR = 'PharmaPulse Export Studio'

function buildCoverSheet(wb: ExcelJS.Workbook, dataset: ExportDataset): void {
  const sheet = wb.addWorksheet('Cover')
  const rows: Array<[string, string | number]> = [
    ['Field', 'Value'],
    ['Report Title', dataset.meta.templateName],
    ['Scope', dataset.meta.scopeLabel],
    ['Period', dataset.meta.periodLabel],
    ['Generated At', dataset.meta.generatedAt],
    ['Generated By', dataset.meta.generatedBy],
    ['Workbook Version', dataset.meta.workbookVersion],
    ['Generator', WORKBOOK_GENERATOR],
    ['Confidentiality', 'Internal — Management Use Only'],
    ['Row Count', dataset.meta.rowCount],
  ]
  if (dataset.meta.warnings.length) rows.push(['Warnings', dataset.meta.warnings.join(' | ')])
  rows.forEach((r) => sheet.addRow(r))
  applySheetQuality(sheet, ['Field', 'Value'])
}

function buildDataSheet(wb: ExcelJS.Workbook, sheet: ExportSheetData): void {
  const ws = wb.addWorksheet(sheet.sheetName.slice(0, 31))
  const headers = sheet.columns.map((c) => c.header)
  ws.addRow(headers)
  for (const row of sheet.rows) {
    ws.addRow(sheet.columns.map((c) => row[c.key] ?? ''))
  }
  applySheetQuality(ws, headers)
  sheet.columns.forEach((col, idx) => {
    const format = formatForUnit(col.unit)
    if (format) applyColumnFormat(ws, idx, format)
  })
}

function buildDefinitionsSheet(wb: ExcelJS.Workbook, dataset: ExportDataset): void {
  const headers = ['Metric', 'Definition', 'Formula', 'Unit', 'Source', 'Exclusions', 'Cap Behavior', 'Missing Target Behavior', 'Ranking Scope', 'Period Logic', 'Notes']
  const ws = wb.addWorksheet('Definitions')
  ws.addRow(headers)
  for (const d of dataset.definitions) {
    ws.addRow([
      d.metric, d.definition, d.formula, d.unit, d.source, d.exclusions, d.capBehavior, d.missingTargetBehavior, d.rankingScope, d.periodLogic, d.notes,
    ])
  }
  applySheetQuality(ws, headers)
}

/** Builds a complete ExcelJS.Workbook from an ExportDataset. Sheet
 *  order: Cover -> each analytical sheet -> Raw Data (if present) ->
 *  Definitions. */
export async function buildExportWorkbook(dataset: ExportDataset): Promise<ExcelJS.Workbook> {
  const { default: ExcelJSRuntime } = await import('exceljs')
  const wb = new ExcelJSRuntime.Workbook()
  wb.creator = WORKBOOK_GENERATOR
  wb.created = new Date(dataset.meta.generatedAt)

  buildCoverSheet(wb, dataset)
  for (const sheet of dataset.sheets) {
    buildDataSheet(wb, sheet)
  }
  if (dataset.rawData) {
    buildDataSheet(wb, dataset.rawData)
  }
  buildDefinitionsSheet(wb, dataset)
  return wb
}

export function buildExportFileName(dataset: ExportDataset, format: 'xlsx' | 'csv'): string {
  const safeScope = dataset.meta.scopeLabel.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40)
  const datePart = dataset.meta.generatedAt.slice(0, 10)
  return `PharmaPulse_${dataset.meta.templateId}_${safeScope}_${datePart}.${format}`
}
