// ============================================================
// Export Studio — Workbook Builder (DX-10)
//
// Pure: ExportDataset -> XLSX.WorkBook. Never writes a file itself
// (see exportDownloadService.ts) and never decides whether the
// workbook is safe to download (see exportValidation.ts) — those are
// separate steps in the pipeline by design.
// ============================================================
import * as XLSX from 'xlsx'
import type { ExportDataset, ExportSheetData } from './exportTypes'
import { applySheetQuality, applyColumnFormat, formatForUnit } from './exportStyling'

const WORKBOOK_GENERATOR = 'PharmaPulse Export Studio'

function buildCoverSheet(dataset: ExportDataset): XLSX.WorkSheet {
  return XLSX.utils.aoa_to_sheet([
    ['Field', 'Value'],
    ['Report Title', dataset.meta.templateName],
    ['Scope', dataset.meta.scopeLabel],
    ['Period', dataset.meta.periodLabel],
    ['Generated At', dataset.meta.generatedAt],
    ['Generated By', dataset.meta.generatedBy],
    ['Workbook Version', dataset.meta.workbookVersion],
    ['Generator', WORKBOOK_GENERATOR],
    ['Confidentiality', 'Internal — Management Use Only'],
    ['Row Count', dataset.meta.rowCount],
    ...(dataset.meta.warnings.length ? [['Warnings', dataset.meta.warnings.join(' | ')]] : []),
  ])
}

function buildDataSheet(sheet: ExportSheetData): XLSX.WorkSheet {
  const headers = sheet.columns.map((c) => c.header)
  const aoa = [headers, ...sheet.rows.map((row) => sheet.columns.map((c) => row[c.key] ?? ''))]
  const ws = XLSX.utils.aoa_to_sheet(aoa)
  applySheetQuality(ws, headers)
  sheet.columns.forEach((col, idx) => {
    const format = formatForUnit(col.unit)
    if (format) applyColumnFormat(ws, idx, sheet.rows.length, format)
  })
  return ws
}

function buildDefinitionsSheet(dataset: ExportDataset): XLSX.WorkSheet {
  const headers = ['Metric', 'Definition', 'Formula', 'Unit', 'Source', 'Exclusions', 'Cap Behavior', 'Missing Target Behavior', 'Ranking Scope', 'Period Logic', 'Notes']
  const aoa = [headers, ...dataset.definitions.map((d) => [
    d.metric, d.definition, d.formula, d.unit, d.source, d.exclusions, d.capBehavior, d.missingTargetBehavior, d.rankingScope, d.periodLogic, d.notes,
  ])]
  const ws = XLSX.utils.aoa_to_sheet(aoa)
  applySheetQuality(ws, headers)
  return ws
}

/** Builds a complete XLSX.WorkBook from an ExportDataset. Sheet order:
 *  Cover -> each analytical sheet -> Raw Data (if present) -> Definitions. */
export function buildExportWorkbook(dataset: ExportDataset): XLSX.WorkBook {
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, buildCoverSheet(dataset), 'Cover')
  for (const sheet of dataset.sheets) {
    XLSX.utils.book_append_sheet(wb, buildDataSheet(sheet), sheet.sheetName.slice(0, 31))
  }
  if (dataset.rawData) {
    XLSX.utils.book_append_sheet(wb, buildDataSheet(dataset.rawData), dataset.rawData.sheetName.slice(0, 31))
  }
  XLSX.utils.book_append_sheet(wb, buildDefinitionsSheet(dataset), 'Definitions')
  return wb
}

export function buildExportFileName(dataset: ExportDataset, format: 'xlsx' | 'csv'): string {
  const safeScope = dataset.meta.scopeLabel.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40)
  const datePart = dataset.meta.generatedAt.slice(0, 10)
  return `PharmaPulse_${dataset.meta.templateId}_${safeScope}_${datePart}.${format}`
}
