import { describe, it, expect } from 'vitest'
import * as XLSX from 'xlsx'
import { buildExportWorkbook, buildExportFileName } from './workbookBuilder'
import type { ExportDataset } from './exportTypes'

function makeDataset(overrides: Partial<ExportDataset> = {}): ExportDataset {
  return {
    meta: {
      templateId: 'branch-performance', templateName: 'Branch Performance Workbook', workbookVersion: '1.0',
      scopeLabel: 'Branch B001', periodLabel: '2026-06', generatedAt: '2026-06-15T00:00:00.000Z',
      generatedBy: 'admin-1', rowCount: 1, warnings: [],
    },
    sheets: [{
      sheetName: 'Branch Summary',
      columns: [{ key: 'name', header: 'Name', unit: 'number', numeric: false }, { key: 'ach', header: 'Achievement %', unit: 'percentage', numeric: true }],
      rows: [{ name: 'مدينة الرياض', ach: 87.5 }],
    }],
    definitions: [{
      metric: 'Achievement %', definition: 'd', formula: 'f', unit: '%', source: 's', exclusions: 'e',
      capBehavior: 'c', missingTargetBehavior: 'm', rankingScope: 'r', periodLogic: 'p', notes: 'n',
    }],
    ...overrides,
  }
}

describe('DX-10 — Workbook Builder', () => {
  it('builds a workbook with Cover, the data sheet, and Definitions, in that order', () => {
    const wb = buildExportWorkbook(makeDataset())
    expect(wb.SheetNames).toEqual(['Cover', 'Branch Summary', 'Definitions'])
  })

  it('includes a Raw Data sheet right before Definitions when present', () => {
    const dataset = makeDataset({ rawData: { sheetName: 'Raw Data', columns: [{ key: 'name', header: 'Name', unit: 'number', numeric: false }], rows: [{ name: 'x' }] } })
    const wb = buildExportWorkbook(dataset)
    expect(wb.SheetNames).toEqual(['Cover', 'Branch Summary', 'Raw Data', 'Definitions'])
  })

  it('preserves Arabic text in cell values', () => {
    const wb = buildExportWorkbook(makeDataset())
    const sheet = wb.Sheets['Branch Summary']
    const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet)
    expect(rows[0].Name).toBe('مدينة الرياض')
  })

  it('applies autofilter and column widths to every data sheet', () => {
    const wb = buildExportWorkbook(makeDataset())
    const sheet = wb.Sheets['Branch Summary']
    expect(sheet['!autofilter']).toBeDefined()
    expect(sheet['!cols']).toBeDefined()
  })

  it('Cover sheet carries scope, period, generated-by, and confidentiality classification', () => {
    const wb = buildExportWorkbook(makeDataset())
    const cover = XLSX.utils.sheet_to_json<{ Field: string; Value: unknown }>(wb.Sheets['Cover'])
    expect(cover.find((r) => r.Field === 'Scope')?.Value).toBe('Branch B001')
    expect(cover.find((r) => r.Field === 'Generated By')?.Value).toBe('admin-1')
    expect(cover.find((r) => r.Field === 'Confidentiality')?.Value).toBeTruthy()
  })

  it('contains no formulas and no external links', () => {
    const wb = buildExportWorkbook(makeDataset())
    for (const name of wb.SheetNames) {
      const sheet = wb.Sheets[name]
      for (const key of Object.keys(sheet)) {
        if (key.startsWith('!')) continue
        expect((sheet[key] as XLSX.CellObject).f).toBeUndefined()
      }
    }
  })

  it('builds a deterministic, filesystem-safe file name', () => {
    const fileName = buildExportFileName(makeDataset(), 'xlsx')
    expect(fileName).toMatch(/^PharmaPulse_branch-performance_.*\.xlsx$/)
    expect(fileName).not.toMatch(/[\\/:*?"<>|]/)
  })

  it('an empty dataset still produces a valid workbook (headers + Definitions only)', () => {
    const dataset = makeDataset({ sheets: [{ sheetName: 'Branch Summary', columns: [{ key: 'name', header: 'Name', unit: 'number', numeric: false }], rows: [] }] })
    const wb = buildExportWorkbook(dataset)
    expect(wb.SheetNames).toContain('Branch Summary')
    const rows = XLSX.utils.sheet_to_json(wb.Sheets['Branch Summary'])
    expect(rows).toHaveLength(0)
  })
})
