import { describe, it, expect } from 'vitest'
import { buildExportWorkbook, buildExportFileName } from './workbookBuilder'
import type { ExportDataset } from './exportTypes'

function makeDataset(overrides: Partial<ExportDataset> = {}): ExportDataset {
  return {
    meta: {
      templateId: 'branch-performance', templateName: 'Branch Performance Workbook', workbookVersion: '1.0',
      scopeLabel: 'Branch B001', periodLabel: '2026-06', generatedAt: '2026-06-15T00:00:00.000Z',
      generatedBy: 'admin-1', rowCount: 1, warnings: [],
    },
    sheets: [{
      sheetName: 'Branch Summary',
      columns: [{ key: 'name', header: 'Name', unit: 'number', numeric: false }, { key: 'ach', header: 'Achievement %', unit: 'percentage', numeric: true }],
      rows: [{ name: 'مدينة الرياض', ach: 87.5 }],
    }],
    definitions: [{
      metric: 'Achievement %', definition: 'd', formula: 'f', unit: '%', source: 's', exclusions: 'e',
      capBehavior: 'c', missingTargetBehavior: 'm', rankingScope: 'r', periodLogic: 'p', notes: 'n',
    }],
    ...overrides,
  }
}

type Workbook = Awaited<ReturnType<typeof buildExportWorkbook>>

/** Reads a data-sheet row (1-based, header is row 1) as a plain
 *  { header: value } object, following the sheet's own column order —
 *  the ExcelJS equivalent of the old XLSX.utils.sheet_to_json helper. */
function rowAsObject(sheet: ReturnType<Workbook['getWorksheet']>, rowNumber: number) {
  const headerRow = sheet!.getRow(1)
  const row = sheet!.getRow(rowNumber)
  const obj: Record<string, unknown> = {}
  headerRow.eachCell((cell, colNumber) => {
    obj[String(cell.value)] = row.getCell(colNumber).value
  })
  return obj
}

describe('DX-10 — Workbook Builder', () => {
  it('builds a workbook with Cover, the data sheet, and Definitions, in that order', async () => {
    const wb = await buildExportWorkbook(makeDataset())
    expect(wb.worksheets.map((ws) => ws.name)).toEqual(['Cover', 'Branch Summary', 'Definitions'])
  })

  it('includes a Raw Data sheet right before Definitions when present', async () => {
    const dataset = makeDataset({ rawData: { sheetName: 'Raw Data', columns: [{ key: 'name', header: 'Name', unit: 'number', numeric: false }], rows: [{ name: 'x' }] } })
    const wb = await buildExportWorkbook(dataset)
    expect(wb.worksheets.map((ws) => ws.name)).toEqual(['Cover', 'Branch Summary', 'Raw Data', 'Definitions'])
  })

  it('preserves Arabic text in cell values', async () => {
    const wb = await buildExportWorkbook(makeDataset())
    const row = rowAsObject(wb.getWorksheet('Branch Summary'), 2)
    expect(row.Name).toBe('مدينة الرياض')
  })

  it('applies a bold, brand-filled header row, autofilter, a frozen header, and column widths to every data sheet', async () => {
    const wb = await buildExportWorkbook(makeDataset())
    const sheet = wb.getWorksheet('Branch Summary')!
    const headerCell = sheet.getRow(1).getCell(1)
    expect(headerCell.font?.bold).toBe(true)
    expect(headerCell.fill).toMatchObject({ type: 'pattern', pattern: 'solid' })
    expect(sheet.autoFilter).toBeDefined()
    expect(sheet.views?.[0]).toMatchObject({ state: 'frozen', ySplit: 1 })
    expect(sheet.getColumn(1).width).toBeGreaterThan(0)
  })

  it('applies the literal-percent number format to percentage columns', async () => {
    const wb = await buildExportWorkbook(makeDataset())
    const sheet = wb.getWorksheet('Branch Summary')!
    expect(sheet.getColumn(2).numFmt).toBe('0.0"%"')
  })

  it('Cover sheet carries scope, period, generated-by, and confidentiality classification', async () => {
    const wb = await buildExportWorkbook(makeDataset())
    const cover = wb.getWorksheet('Cover')!
    const findValue = (field: string) => {
      let value: unknown
      cover.eachRow((row) => {
        if (row.getCell(1).value === field) value = row.getCell(2).value
      })
      return value
    }
    expect(findValue('Scope')).toBe('Branch B001')
    expect(findValue('Generated By')).toBe('admin-1')
    expect(findValue('Confidentiality')).toBeTruthy()
  })

  it('contains no formulas', async () => {
    const wb = await buildExportWorkbook(makeDataset())
    for (const sheet of wb.worksheets) {
      sheet.eachRow((row) => {
        row.eachCell((cell) => {
          expect(cell.formula).toBeUndefined()
        })
      })
    }
  })

  it('builds a deterministic, filesystem-safe file name', () => {
    const fileName = buildExportFileName(makeDataset(), 'xlsx')
    expect(fileName).toMatch(/^PharmaPulse_branch-performance_.*\.xlsx$/)
    expect(fileName).not.toMatch(/[\\/:*?"<>|]/)
  })

  it('an empty dataset still produces a valid workbook (headers + Definitions only)', async () => {
    const dataset = makeDataset({ sheets: [{ sheetName: 'Branch Summary', columns: [{ key: 'name', header: 'Name', unit: 'number', numeric: false }], rows: [] }] })
    const wb = await buildExportWorkbook(dataset)
    const sheet = wb.getWorksheet('Branch Summary')!
    expect(sheet.rowCount).toBe(1) // header row only
  })
})
