// ============================================================
// Insight Engine — Types (Phase 6B)
//
// TypeScript-only data model for explainable, human-readable
// insights. Every narrative string is generated by template
// interpolation over already-computed numbers — never AI, never
// a black box.
//
// No Firestore. No React. No executable logic.
// ============================================================

import type { OpportunityItem } from './opportunityTypes'
import type { TrendDirection } from '../evaluationLedger/ranking/trendTypes'

export type InsightCategory = 'STRENGTH' | 'RISK' | 'OPPORTUNITY'

export interface InsightItem {
  category:     InsightCategory
  title:        string
  description:  string
  /** The underlying numeric value this insight is grounded in. */
  metricValue:  number
  relatedId?:   string
}

export interface ExecutiveSummary {
  entityId:      string
  headline:      string
  narrative:     string
  strengths:     InsightItem[]
  risks:         InsightItem[]
  opportunities: InsightItem[]
  generatedAt:   string
}

export interface InsightAnalysisInput {
  entityId:           string
  overallScore:       number
  opportunityItems:   OpportunityItem[]
  trendDirection?:    TrendDirection
  momentum?:          number
  benchmarkAverage?:  number
}
