// ============================================================
// ExecutiveSummaryCard — Headline + narrative (Phase 6E)
//
// Pure presentational. Displays exactly the fields produced by the
// existing buildExecutiveSummary() kernel. The narrative text is
// template-generated by the kernel from real numbers — this
// component does not generate or alter any text.
// ============================================================
import React from 'react'
import { FileText } from 'lucide-react'

export default function ExecutiveSummaryCard({ summary }) {
  if (!summary) return null

  return (
    <div style={{
      background: 'var(--bg-elevated)', border: '1px solid var(--border-subtle)',
      borderRadius: '8px', padding: '12px', marginBottom: '10px',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
        <FileText style={{ width: 14, height: 14, color: 'var(--text-muted)' }} strokeWidth={1.5} />
        <span style={{ fontSize: '13px', fontWeight: 600, color: 'var(--text-primary)' }}>{summary.headline}</span>
      </div>
      <div style={{ fontSize: '11px', color: 'var(--text-secondary)', lineHeight: 1.5 }}>{summary.narrative}</div>
      <div style={{ display: 'flex', gap: '14px', marginTop: '8px', fontSize: '10px', color: 'var(--text-muted)' }}>
        <span>{summary.strengths.length} strengths</span>
        <span>{summary.risks.length} risks</span>
        <span>{summary.opportunities.length} opportunities</span>
      </div>
    </div>
  )
}
