import { describe, it, expect } from 'vitest'
import * as XLSX from 'xlsx'
import {
  buildKpiRegistryTemplate, buildBranchTargetsTemplate, buildPharmacistTargetsTemplate,
  buildBranchActualsTemplate, buildPharmacistActualsTemplate, buildOrganizationOnboardingTemplate,
  TEMPLATE_VERSION,
} from './templateGenerator'

function headerRow(wb: XLSX.WorkBook, sheetName: string): string[] {
  const sheet = wb.Sheets[sheetName]
  const rows = XLSX.utils.sheet_to_json<string[]>(sheet, { header: 1 })
  return rows[0] as string[]
}

function metadataValue(wb: XLSX.WorkBook, field: string): string | undefined {
  const rows = XLSX.utils.sheet_to_json<{ Field: string; Value: string }>(wb.Sheets['Metadata'])
  return rows.find((r) => r.Field === field)?.Value
}

describe('KPI & Targets Bundle — Excel template generator', () => {
  it('KPI Registry template has the canonical headers, an example row, a Metadata sheet, and an Instructions sheet', () => {
    const wb = buildKpiRegistryTemplate()
    expect(wb.SheetNames).toEqual(['KPI Registry', 'Metadata', 'Instructions'])
    const headers = headerRow(wb, 'KPI Registry')
    expect(headers).toEqual([
      'KPI Key', 'KPI Name English', 'KPI Name Arabic', 'Description English', 'Description Arabic',
      'Unit', 'Category', 'Lifecycle Stage', 'Dashboard Enabled', 'Evaluation Enabled', 'Target Enabled',
      'Direction', 'Aggregation Method', 'Decimal Precision', 'Minimum Value', 'Maximum Value', 'Active', 'Sort Order',
    ])
    const rows = XLSX.utils.sheet_to_json(wb.Sheets['KPI Registry'])
    expect(rows).toHaveLength(1)
  })

  it('Branch Targets template has exactly the 4 canonical columns', () => {
    const wb = buildBranchTargetsTemplate()
    expect(headerRow(wb, 'Branch Targets')).toEqual(['Month', 'Branch Code', 'KPI Key', 'Target Value'])
  })

  it('Pharmacist Targets template has exactly the 5 canonical columns', () => {
    const wb = buildPharmacistTargetsTemplate()
    expect(headerRow(wb, 'Pharmacist Targets')).toEqual(['Month', 'Pharmacist Identifier', 'Branch Code', 'KPI Key', 'Target Value'])
  })

  it('no template embeds production data or sensitive user data — example rows use synthetic identifiers', () => {
    const wb = buildPharmacistTargetsTemplate()
    const rows = XLSX.utils.sheet_to_json<Record<string, string>>(wb.Sheets['Pharmacist Targets'])
    expect(rows[0]['Pharmacist Identifier']).toBe('EMP1024')
    expect(rows[0]['Pharmacist Identifier']).not.toContain('@')
  })

  it('Branch Actuals template has exactly the 4 canonical columns', () => {
    const wb = buildBranchActualsTemplate()
    expect(wb.SheetNames).toEqual(['Branch Actuals', 'Metadata', 'Instructions'])
    expect(headerRow(wb, 'Branch Actuals')).toEqual(['Date', 'Branch Code', 'KPI Key', 'Actual Value'])
  })

  it('Pharmacist Actuals template has exactly the 5 canonical columns', () => {
    const wb = buildPharmacistActualsTemplate()
    expect(wb.SheetNames).toEqual(['Pharmacist Actuals', 'Metadata', 'Instructions'])
    expect(headerRow(wb, 'Pharmacist Actuals')).toEqual(['Date', 'Pharmacist Identifier', 'Branch Code', 'KPI Key', 'Actual Value'])
  })

  it('no actuals template embeds production data or sensitive user data — example rows use synthetic identifiers', () => {
    const wb = buildPharmacistActualsTemplate()
    const rows = XLSX.utils.sheet_to_json<Record<string, string>>(wb.Sheets['Pharmacist Actuals'])
    expect(rows[0]['Pharmacist Identifier']).toBe('EMP1024')
    expect(rows[0]['Pharmacist Identifier']).not.toContain('@')
  })

  describe('DX-8 — Template versioning, metadata, and workbook quality', () => {
    const builders = [
      ['Organization Onboarding', buildOrganizationOnboardingTemplate, 'Groups'] as const,
      ['KPI Registry', buildKpiRegistryTemplate, 'KPI Registry'] as const,
      ['Branch Targets', buildBranchTargetsTemplate, 'Branch Targets'] as const,
      ['Pharmacist Targets', buildPharmacistTargetsTemplate, 'Pharmacist Targets'] as const,
      ['Branch Actuals', buildBranchActualsTemplate, 'Branch Actuals'] as const,
      ['Pharmacist Actuals', buildPharmacistActualsTemplate, 'Pharmacist Actuals'] as const,
    ]

    it.each(builders)('%s template carries a Metadata sheet with name/version/domain/expected sheet', (_label, build, firstDataSheet) => {
      const wb = build()
      expect(wb.SheetNames).toContain('Metadata')
      expect(wb.SheetNames).toContain('Instructions')
      expect(wb.SheetNames[0]).toBe(firstDataSheet)
      expect(metadataValue(wb, 'Template Version')).toBe(TEMPLATE_VERSION)
      expect(metadataValue(wb, 'Template Name')).toBeTruthy()
      expect(metadataValue(wb, 'Import Domain')).toBeTruthy()
      expect(metadataValue(wb, 'Expected Sheet')).toBeTruthy()
      expect(metadataValue(wb, 'Generated By')).toBe('PharmaPulse Data Exchange Studio')
    })

    it.each(builders)('%s data sheet has autofilter and column widths applied', (_label, build, firstDataSheet) => {
      const wb = build()
      const sheet = wb.Sheets[firstDataSheet]
      expect(sheet['!autofilter']).toBeTruthy()
      expect(sheet['!cols']).toBeTruthy()
      expect((sheet['!cols'] as unknown[]).length).toBeGreaterThan(0)
    })

    it('template generation is deterministic — two builds produce identical headers, metadata, and example values', () => {
      const a = buildBranchActualsTemplate()
      const b = buildBranchActualsTemplate()
      expect(headerRow(a, 'Branch Actuals')).toEqual(headerRow(b, 'Branch Actuals'))
      expect(metadataValue(a, 'Template Version')).toBe(metadataValue(b, 'Template Version'))
      expect(XLSX.utils.sheet_to_json(a.Sheets['Branch Actuals'])).toEqual(XLSX.utils.sheet_to_json(b.Sheets['Branch Actuals']))
    })
  })

  describe('DX-8 — Organization Onboarding template (closure gap filled)', () => {
    it('has all four onboarding sheets with their canonical columns', () => {
      const wb = buildOrganizationOnboardingTemplate()
      expect(wb.SheetNames).toEqual(['Groups', 'Branches', 'Pharmacists', 'Assignments', 'Metadata', 'Instructions'])
      expect(headerRow(wb, 'Groups')).toEqual(['Code', 'Name', 'Region', 'Manager', 'Status'])
      expect(headerRow(wb, 'Branches')).toEqual(['Code', 'Name', 'Region', 'City', 'Group', 'Manager', 'Status'])
      expect(headerRow(wb, 'Pharmacists')).toEqual(['Employee ID', 'Name', 'Email', 'Phone', 'Role', 'Branch', 'Joining Date', 'Leaving Date', 'Status'])
      expect(headerRow(wb, 'Assignments')).toEqual(['Employee ID', 'Branch', 'Assignment Type', 'Start Date', 'End Date'])
    })

    it('no onboarding template embeds a real email or phone number — example rows use synthetic identifiers', () => {
      const wb = buildOrganizationOnboardingTemplate()
      const pharmacists = XLSX.utils.sheet_to_json<Record<string, string>>(wb.Sheets['Pharmacists'])
      expect(pharmacists[0].Email).toBe('pharmacist@example.com')
      expect(pharmacists[0]['Employee ID']).toBe('EMP1024')
    })
  })
})
