// ============================================================
// Template Domain Guard.
//
// Every workbook generated by templateGenerator.ts already carries an
// 'Import Domain' row on its Metadata sheet (see buildMetadataSheet).
// This guard reads that row back and compares it against the
// currently-selected importer BEFORE any import_jobs document is
// created — preventing a Pharmacist Actuals file from being run
// through the Branch Actuals importer (or any other domain
// combination), which previously produced confusing
// row-level validation errors instead of a clear, upfront message.
//
// A workbook with no Metadata sheet, or no 'Import Domain' row, is a
// legacy file (predates this guard) or a hand-built file — same
// "never reject what we can't read" posture as templateVersionGuard.ts.
// ============================================================

export interface DomainCheckResult {
  /** true when the workbook's declared domain matches the selected
   *  importer, OR the workbook has no declared domain to check at all. */
  valid: boolean
  /** The domain string declared on the workbook's Metadata sheet, or
   *  null if the workbook declares none (legacy/hand-built file). */
  declaredDomain: string | null
  reason?: string
}

/** Reads the 'Import Domain' row from a parsed Metadata sheet (rows
 *  already converted via XLSX.utils.sheet_to_json, same shape
 *  templateVersionGuard.ts's readTemplateVersion() reads). */
export function readWorkbookDomain(metadataRows: Array<Record<string, unknown>> | undefined): string | null {
  if (!metadataRows || metadataRows.length === 0) return null
  for (const row of metadataRows) {
    if (row.Field === 'Import Domain') {
      const value = row.Value
      return value == null ? null : String(value)
    }
  }
  return null
}

/** Pure check — no Firestore, no file I/O, no import_jobs creation.
 *  Callers parse the workbook once and pass the already-extracted
 *  Metadata sheet rows (or undefined if no Metadata sheet exists) plus
 *  the domain identifier of the importer the user currently has
 *  selected. */
export function checkWorkbookDomain(
  metadataRows:    Array<Record<string, unknown>> | undefined,
  selectedDomain:  string,
): DomainCheckResult {
  const declaredDomain = readWorkbookDomain(metadataRows)

  if (declaredDomain == null) {
    // No Metadata sheet, or no Import Domain row — nothing to check
    // against. Never reject a file for missing metadata we can't read.
    return { valid: true, declaredDomain: null }
  }

  if (declaredDomain === selectedDomain) {
    return { valid: true, declaredDomain }
  }

  return {
    valid: false,
    declaredDomain,
    reason: `Template domain mismatch:\nThis workbook is ${declaredDomain},\nbut the selected importer is ${selectedDomain}.`,
  }
}
