// ============================================================
// Data Exchange Studio — downloadable Excel import templates
// (DX-4/DX-5/DX-6, hardened in DX-8)
//
// Generates client-side .xlsx workbooks with canonical headers, one
// realistic example row, a visible Metadata sheet (template name/
// version/domain/expected sheet/format rules), and an Instructions
// sheet. No production data, no sensitive user data, ever embedded.
// This module ONLY builds import templates — it is not the future
// Premium Export Studio.
//
// DX-8 versioning model (intentionally the smallest maintainable
// shape — no migration framework): every workbook carries a single,
// stable TEMPLATE_VERSION string on its Metadata sheet. A workbook
// with NO Metadata sheet at all predates DX-8 and is treated as a
// legacy, still-supported version (see templateVersionGuard.ts) —
// every column/validation rule below is unchanged for those files.
// A workbook whose Metadata sheet names a version not in
// SUPPORTED_TEMPLATE_VERSIONS is rejected with a clear error before
// any row parsing happens, never a crash.
//
// Workbook quality notes (honest limitations, not silently skipped):
// the installed SheetJS Community Edition (xlsx@0.18.5) does not
// support writing frozen panes or in-cell dropdown data-validation
// lists — both are Pro-only features in this library. Autofilter and
// column widths ARE supported and are applied to every data sheet.
// Allowed-value guidance is therefore textual, in the Instructions
// sheet, sourced from the same real enums the adapters validate
// against (see ALLOWED_VALUES below) rather than a fabricated list.
// ============================================================

import * as XLSX from 'xlsx'

export const TEMPLATE_VERSION = '1.0'

// Real enums, not invented — mirrors what the adapters actually
// validate against (kpiRegistryTypes.ts / branchTargetsAdapter.ts /
// branchActualsAdapter.ts), kept here as plain strings so this module
// has no runtime dependency on the engine package.
export const ALLOWED_VALUES = {
  kpiCategory:        ['prescription', 'digital', 'wellness', 'commercial', 'operational', 'health_program'],
  kpiDirection:        ['higher_is_better', 'lower_is_better'],
  kpiLifecycleStage:   ['draft', 'pilot_tracking', 'shadow_evaluation', 'production_evaluation', 'archived'],
  kpiAggregationMethod: ['SUM', 'AVG', 'RATIO', 'NOT_AGGREGATED'],
  booleanLike:         ['TRUE', 'FALSE', '1', '0', 'yes', 'no'],
  pharmacistRole:      ['pharmacist', 'manager', 'branch_manager', 'district_supervisor', 'regional_manager'],
  assignmentType:      ['primary', 'secondary'],
  recordStatus:        ['active', 'inactive'],
} as const

export interface TemplateMeta {
  templateName:    string
  domain:          string
  expectedSheet:   string
  dateFormat?:     string
  monthFormat?:    string
  identifierRules?: string
}

function autoSize(headers: string[]): XLSX.ColInfo[] {
  return headers.map((h) => ({ wch: Math.max(14, h.length + 2) }))
}

function applyDataSheetQuality(sheet: XLSX.WorkSheet, headers: string[]): void {
  // Autofilter + column widths are genuinely supported by the writer
  // (verified against the installed SheetJS CE version) — frozen
  // panes and data-validation dropdowns are not, see module header.
  sheet['!autofilter'] = { ref: XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: 0, c: headers.length - 1 } }) }
  sheet['!cols'] = autoSize(headers)
}

function buildMetadataSheet(meta: TemplateMeta): XLSX.WorkSheet {
  return XLSX.utils.aoa_to_sheet([
    ['Field', 'Value'],
    ['Template Name', meta.templateName],
    ['Template Version', TEMPLATE_VERSION],
    ['Import Domain', meta.domain],
    ['Generated By', 'PharmaPulse Data Exchange Studio'],
    ['Expected Sheet', meta.expectedSheet],
    ['Date Format', meta.dateFormat || 'n/a'],
    ['Month Format', meta.monthFormat || 'n/a'],
    ['Identifier Rules', meta.identifierRules || 'n/a'],
  ])
}

function buildWorkbook(
  sheetName: string, headers: string[], exampleRow: Record<string, string>,
  instructions: string[][], meta: TemplateMeta,
): XLSX.WorkBook {
  const wb = XLSX.utils.book_new()

  const dataSheet = XLSX.utils.json_to_sheet([exampleRow], { header: headers })
  applyDataSheetQuality(dataSheet, headers)
  XLSX.utils.book_append_sheet(wb, dataSheet, sheetName)

  XLSX.utils.book_append_sheet(wb, buildMetadataSheet(meta), 'Metadata')

  const instructionsSheet = XLSX.utils.aoa_to_sheet(instructions)
  XLSX.utils.book_append_sheet(wb, instructionsSheet, 'Instructions')

  return wb
}

/** Multi-sheet variant for Organization Onboarding — one workbook,
 *  several domain sheets, one shared Metadata + Instructions sheet,
 *  matching onboardingOrchestrator.ts's existing flat-4-sheet
 *  upload shape (it never supported arbitrary nested structures). */
function buildMultiSheetWorkbook(
  sheets: Array<{ sheetName: string; headers: string[]; exampleRow: Record<string, string> }>,
  instructions: string[][], meta: TemplateMeta,
): XLSX.WorkBook {
  const wb = XLSX.utils.book_new()

  for (const s of sheets) {
    const dataSheet = XLSX.utils.json_to_sheet([s.exampleRow], { header: s.headers })
    applyDataSheetQuality(dataSheet, s.headers)
    XLSX.utils.book_append_sheet(wb, dataSheet, s.sheetName)
  }

  XLSX.utils.book_append_sheet(wb, buildMetadataSheet(meta), 'Metadata')

  const instructionsSheet = XLSX.utils.aoa_to_sheet(instructions)
  XLSX.utils.book_append_sheet(wb, instructionsSheet, 'Instructions')

  return wb
}

function download(wb: XLSX.WorkBook, fileName: string): void {
  XLSX.writeFile(wb, fileName)
}

// ── DX-2/DX-3: Organization Onboarding (Groups / Branches / Pharmacists / Assignments) ──
// Closure gap filled in DX-8 — no downloadable template existed for
// this bundle before now, even though the adapters/orchestrator did.

const GROUPS_HEADERS       = ['Code', 'Name', 'Region', 'Manager', 'Status']
const BRANCHES_HEADERS     = ['Code', 'Name', 'Region', 'City', 'Group', 'Manager', 'Status']
const PHARMACISTS_HEADERS  = ['Employee ID', 'Name', 'Email', 'Phone', 'Role', 'Branch', 'Joining Date', 'Leaving Date', 'Status']
const ASSIGNMENTS_HEADERS  = ['Employee ID', 'Branch', 'Assignment Type', 'Start Date', 'End Date']

export function buildOrganizationOnboardingTemplate(): XLSX.WorkBook {
  return buildMultiSheetWorkbook(
    [
      { sheetName: 'Groups', headers: GROUPS_HEADERS, exampleRow: { Code: 'G001', Name: 'Central Region Group', Region: 'R01', Manager: '', Status: 'active' } },
      { sheetName: 'Branches', headers: BRANCHES_HEADERS, exampleRow: { Code: 'B001', Name: 'Downtown Pharmacy', Region: 'R01', City: 'Riyadh', Group: 'G001', Manager: 'manager@example.com', Status: 'active' } },
      { sheetName: 'Pharmacists', headers: PHARMACISTS_HEADERS, exampleRow: { 'Employee ID': 'EMP1024', Name: 'Sample Pharmacist', Email: 'pharmacist@example.com', Phone: '0500000000', Role: 'pharmacist', Branch: 'B001', 'Joining Date': '2026-01-01', 'Leaving Date': '', Status: 'active' } },
      { sheetName: 'Assignments', headers: ASSIGNMENTS_HEADERS, exampleRow: { 'Employee ID': 'EMP1024', Branch: 'B001', 'Assignment Type': 'primary', 'Start Date': '2026-01-01', 'End Date': '' } },
    ],
    [
      ['Organization Onboarding Import — Instructions'],
      [''],
      ['One workbook, four sheets: Groups, Branches, Pharmacists, Assignments. Each sheet may also be uploaded'],
      ['as its own single-sheet file — the sheet name (not the file name) determines its domain.'],
      [''],
      ['Groups: Code and Name are required. Region (optional) must match an existing region code. Manager'],
      ['(optional) is a manager UID. Status accepts active/inactive (defaults to active if blank).'],
      [''],
      ['Branches: Code and Name are required. Group (optional) links to an existing Group code. Manager'],
      ['(optional) accepts a manager email. Status accepts active/inactive (defaults to active if blank).'],
      [''],
      ['Pharmacists: Employee ID and Name are required. Role must be one of: ' + ALLOWED_VALUES.pharmacistRole.join(', ') + '.'],
      ['Branch (optional) links to an existing Branch code. Joining/Leaving Date use YYYY-MM-DD. Imported'],
      ['pharmacists are created as pending-invitation operational records only — no Firebase Auth account or'],
      ['password is ever created by bulk import; activation remains the existing manual createUser() flow.'],
      [''],
      ['Assignments: Employee ID and Branch are required. Assignment Type must be one of: primary, secondary.'],
      ['Start/End Date use YYYY-MM-DD.'],
      [''],
      ['Commit order is always Groups -> Branches -> Pharmacists -> Assignments, regardless of sheet order in'],
      ['your file, so a Pharmacist row can reference a Branch created earlier in the same import.'],
      [''],
      ['Existing records: a different value for an existing Code/Employee ID is staged as an UPDATE and shown'],
      ['with the old vs new value in the preview — nothing is written until you explicitly confirm and commit.'],
      ['A pending identity that has since been claimed/activated by a real account is never matched against'],
      ['its old, superseded record (CLAIMED records are excluded from identifier resolution).'],
    ],
    { templateName: 'Organization Onboarding', domain: 'GROUP, BRANCH, PHARMACIST, ASSIGNMENT', expectedSheet: 'Groups, Branches, Pharmacists, Assignments', dateFormat: 'YYYY-MM-DD', identifierRules: 'Employee ID (pharmacists), Code (groups/branches)' },
  )
}

export function downloadOrganizationOnboardingTemplate(): void {
  download(buildOrganizationOnboardingTemplate(), 'PharmaPulse_Organization_Onboarding_Import_Template.xlsx')
}

// ── DX-4: KPI Registry ──────────────────────────────────────────

const KPI_REGISTRY_HEADERS = [
  'KPI Key', 'KPI Name English', 'KPI Name Arabic', 'Description English', 'Description Arabic',
  'Unit', 'Category', 'Lifecycle Stage', 'Dashboard Enabled', 'Evaluation Enabled', 'Target Enabled',
  'Direction', 'Aggregation Method', 'Decimal Precision', 'Minimum Value', 'Maximum Value', 'Active', 'Sort Order',
]

export function buildKpiRegistryTemplate(): XLSX.WorkBook {
  return buildWorkbook('KPI Registry', KPI_REGISTRY_HEADERS, {
    'KPI Key': 'inboundCalls', 'KPI Name English': 'Inbound Calls', 'KPI Name Arabic': 'المكالمات الواردة',
    'Description English': 'Total inbound customer calls handled this month', 'Description Arabic': '',
    Unit: 'calls', Category: 'operational', 'Lifecycle Stage': 'pilot_tracking',
    'Dashboard Enabled': 'TRUE', 'Evaluation Enabled': 'FALSE', 'Target Enabled': 'FALSE',
    Direction: 'higher_is_better', 'Aggregation Method': 'SUM', 'Decimal Precision': '', 'Minimum Value': '', 'Maximum Value': '',
    Active: 'TRUE', 'Sort Order': '999',
  }, [
    ['KPI Registry Import — Instructions'],
    [''],
    ['Required columns: KPI Key, KPI Name English, Unit, Category, Direction.'],
    ['KPI Key must be camelCase letters/numbers only (e.g. inboundCalls), and must be unique (case-insensitively).'],
    ['Category must be one of: ' + ALLOWED_VALUES.kpiCategory.join(', ') + '.'],
    ['Direction must be one of: ' + ALLOWED_VALUES.kpiDirection.join(', ') + '.'],
    ['Lifecycle Stage must be one of: ' + ALLOWED_VALUES.kpiLifecycleStage.join(', ') + '.'],
    ['  New KPIs default to draft if left blank. Evaluation Enabled = TRUE defaults a blank Lifecycle Stage to production_evaluation;'],
    ['  Evaluation Enabled = FALSE defaults it to pilot_tracking. An explicit Lifecycle Stage always wins over Evaluation Enabled.'],
    ['Aggregation Method (optional) must be one of: ' + ALLOWED_VALUES.kpiAggregationMethod.join(', ') + '.'],
    ['Dashboard Enabled / Target Enabled / Active accept ' + ALLOWED_VALUES.booleanLike.join(', ') + '.'],
    [''],
    ['KNOWN DEVIATIONS — these columns are accepted for transparency but have NO field in the'],
    ['production KPI Registry and are never stored. They exist so nothing in your source file is silently dropped:'],
    ['  Description Arabic — the registry stores only one English description field.'],
    ['  Decimal Precision — not part of the registry contract.'],
    ['  Minimum Value / Maximum Value — the registry uses achievement-% thresholds (healthy/watch/risk/critical),'],
    ['    not raw value clamps. These columns are sanity-checked (min <= max) but never persisted.'],
    [''],
    ['Existing KPIs: unit, direction, lifecycle stage, aggregation method, and target-enabled changes are'],
    ['treated as CONFLICTS requiring explicit review — they are never silently overwritten. The 5 protected'],
    ['core KPIs (wasfaty, omnihealth, wellnessCard, basket, crossSelling) cannot be modified by bulk import at all.'],
  ], { templateName: 'KPI Registry', domain: 'KPI_REGISTRY', expectedSheet: 'KPI Registry' })
}

export function downloadKpiRegistryTemplate(): void {
  download(buildKpiRegistryTemplate(), 'PharmaPulse_KPI_Registry_Import_Template.xlsx')
}

// ── DX-5a: Branch Targets ────────────────────────────────────────

const BRANCH_TARGETS_HEADERS = ['Month', 'Branch Code', 'KPI Key', 'Target Value']

export function buildBranchTargetsTemplate(): XLSX.WorkBook {
  return buildWorkbook('Branch Targets', BRANCH_TARGETS_HEADERS, {
    Month: '2026-06', 'Branch Code': 'B001', 'KPI Key': 'wasfaty', 'Target Value': '300000',
  }, [
    ['Branch Targets Import — Instructions'],
    [''],
    ['All four columns are required: Month, Branch Code, KPI Key, Target Value.'],
    ['Month must be in YYYY-MM format (e.g. 2026-06). 2026/06 and 2026-6 are also accepted and normalized.'],
    ['Branch Code must match an existing, active branch code exactly.'],
    ['KPI Key must match an existing KPI that is target-enabled and not archived (see the KPI Registry).'],
    ['Target Value must be a non-negative number. Use 0 for an explicit zero target — simply omit the row'],
    ['entirely to leave an existing target untouched (0 and "no row" are never treated the same).'],
    ['One row per Branch + Month + KPI. Each branch+month accumulates one production document per KPI field —'],
    ['importing multiple KPI rows for the same branch+month is safe and does not overwrite other KPIs.'],
    [''],
    ['KNOWN DEVIATIONS — Notes, Source, Effective Date, and Status were considered but have no field in the'],
    ['production targets document contract, so they are intentionally excluded from this template.'],
    [''],
    ['Existing targets: a different Target Value for the same Branch+Month+KPI is staged as an UPDATE and shown'],
    ['with the old vs new value in the preview — nothing is written until you explicitly confirm and commit.'],
  ], { templateName: 'Branch Targets', domain: 'BRANCH_TARGET', expectedSheet: 'Branch Targets', monthFormat: 'YYYY-MM' })
}

export function downloadBranchTargetsTemplate(): void {
  download(buildBranchTargetsTemplate(), 'PharmaPulse_Branch_Targets_Import_Template.xlsx')
}

// ── DX-5b: Pharmacist Targets ────────────────────────────────────

const PHARMACIST_TARGETS_HEADERS = ['Month', 'Pharmacist Identifier', 'Branch Code', 'KPI Key', 'Target Value']

export function buildPharmacistTargetsTemplate(): XLSX.WorkBook {
  return buildWorkbook('Pharmacist Targets', PHARMACIST_TARGETS_HEADERS, {
    Month: '2026-06', 'Pharmacist Identifier': 'EMP1024', 'Branch Code': 'B001', 'KPI Key': 'wasfaty', 'Target Value': '100000',
  }, [
    ['Pharmacist Targets Import — Instructions'],
    [''],
    ['All five columns are required: Month, Pharmacist Identifier, Branch Code, KPI Key, Target Value.'],
    ['Pharmacist Identifier accepts an Employee ID (preferred), a real account email, or a real user UID —'],
    ['resolved in that order. A pending-onboarding identity that has since been claimed/activated is never'],
    ['matched against its old, superseded record — only the active operational identity resolves.'],
    ['Month, KPI Key, and Target Value follow the exact same rules as the Branch Targets template.'],
    ['Branch Code must be the pharmacist\'s own assigned branch — a mismatch is rejected, not silently moved.'],
    ['One row per Pharmacist + Branch + Month + KPI. Multiple KPI rows for the same pharmacist+month'],
    ['accumulate safely into one personal target record without overwriting other KPIs.'],
    [''],
    ['Deactivated pharmacists and unresolved/ambiguous identities are rejected, not silently skipped —'],
    ['every rejected row is reported with the exact reason in the preview.'],
    [''],
    ['Existing targets: a different Target Value for the same Pharmacist+Branch+Month+KPI is staged as an'],
    ['UPDATE and shown with the old vs new value in the preview — nothing is written until you confirm.'],
    ['Imported targets are saved as drafts — publish them from the existing Personal Targets page when ready.'],
  ], { templateName: 'Pharmacist Targets', domain: 'PHARMACIST_TARGET', expectedSheet: 'Pharmacist Targets', monthFormat: 'YYYY-MM', identifierRules: 'Employee ID > email > UID' })
}

export function downloadPharmacistTargetsTemplate(): void {
  download(buildPharmacistTargetsTemplate(), 'PharmaPulse_Pharmacist_Targets_Import_Template.xlsx')
}

// ── DX-6: Branch Actuals ─────────────────────────────────────────

const BRANCH_ACTUALS_HEADERS = ['Date', 'Branch Code', 'KPI Key', 'Actual Value']

export function buildBranchActualsTemplate(): XLSX.WorkBook {
  return buildWorkbook('Branch Actuals', BRANCH_ACTUALS_HEADERS, {
    Date: '2026-06-04', 'Branch Code': 'B001', 'KPI Key': 'wasfaty', 'Actual Value': '8200',
  }, [
    ['Branch Actuals Import — Instructions'],
    [''],
    ['All four columns are required: Date, Branch Code, KPI Key, Actual Value.'],
    ['Date must be in YYYY-MM-DD format (e.g. 2026-06-04). 2026/06/04 is also accepted and normalized.'],
    ['Date cannot be in the future relative to today.'],
    ['Branch Code must match an existing, active branch code exactly.'],
    ['KPI Key must match an existing KPI that is active, in production_evaluation, and dashboard-enabled.'],
    ['Actual Value must be a non-negative number. Use 0 for an explicit zero actual — simply omit the row'],
    ['entirely to leave an existing actual untouched (0 and "no row" are never treated the same).'],
    ['One row per Branch + Date + KPI. Each branch+date accumulates one production entry document per KPI'],
    ['field — importing multiple KPI rows for the same branch+date is safe and does not overwrite other KPIs.'],
    [''],
    ['KNOWN DEVIATION (resolved ambiguity, documented): there is no branch-only actuals record in the production'],
    ['system — every KPI entry belongs to a specific user. A Branch Actual is therefore written under the'],
    ['branch\'s assigned MANAGER as the entry owner. A branch with no manager assigned cannot receive a'],
    ['Branch Actual import row — that row is rejected with a clear reason, never silently attributed elsewhere.'],
    [''],
    ['Existing actuals: a different Actual Value for the same Branch+Date+KPI is staged as an UPDATE and shown'],
    ['with the old vs new value in the preview — nothing is written until you explicitly confirm and commit.'],
  ], { templateName: 'Branch Actuals', domain: 'BRANCH_ACTUALS', expectedSheet: 'Branch Actuals', dateFormat: 'YYYY-MM-DD' })
}

export function downloadBranchActualsTemplate(): void {
  download(buildBranchActualsTemplate(), 'PharmaPulse_Branch_Actuals_Import_Template.xlsx')
}

// ── DX-6: Pharmacist Actuals ──────────────────────────────────────

const PHARMACIST_ACTUALS_HEADERS = ['Date', 'Pharmacist Identifier', 'Branch Code', 'KPI Key', 'Actual Value']

export function buildPharmacistActualsTemplate(): XLSX.WorkBook {
  return buildWorkbook('Pharmacist Actuals', PHARMACIST_ACTUALS_HEADERS, {
    Date: '2026-06-04', 'Pharmacist Identifier': 'EMP1024', 'Branch Code': 'B001', 'KPI Key': 'wasfaty', 'Actual Value': '4100',
  }, [
    ['Pharmacist Actuals Import — Instructions'],
    [''],
    ['All five columns are required: Date, Pharmacist Identifier, Branch Code, KPI Key, Actual Value.'],
    ['Pharmacist Identifier accepts an Employee ID (preferred), a real account email, or a real user UID —'],
    ['resolved in that order. A pending-onboarding identity that has since been claimed/activated is never'],
    ['matched against its old, superseded record — only the active operational identity resolves.'],
    ['Date, KPI Key, and Actual Value follow the exact same rules as the Branch Actuals template.'],
    ['Branch Code must be the pharmacist\'s own assigned branch — a mismatch is rejected, not silently moved.'],
    ['One row per Pharmacist + Branch + Date + KPI. Multiple KPI rows for the same pharmacist+date'],
    ['accumulate safely into one entry record without overwriting other KPIs.'],
    [''],
    ['Deactivated pharmacists and unresolved/ambiguous identities are rejected, not silently skipped —'],
    ['every rejected row is reported with the exact reason in the preview.'],
    [''],
    ['Existing actuals: a different Actual Value for the same Pharmacist+Branch+Date+KPI is staged as an'],
    ['UPDATE and shown with the old vs new value in the preview — nothing is written until you confirm.'],
    [''],
    ['LARGE FILES: files are capped per import (see the in-app limit shown on the upload screen). Very large'],
    ['files are parsed and validated in chunks to keep your browser responsive, with progress shown live, and a'],
    ['paused or partially-completed import can always be safely resumed or retried without duplicating rows.'],
  ], { templateName: 'Pharmacist Actuals', domain: 'PHARMACIST_ACTUALS', expectedSheet: 'Pharmacist Actuals', dateFormat: 'YYYY-MM-DD', identifierRules: 'Employee ID > email > UID' })
}

export function downloadPharmacistActualsTemplate(): void {
  download(buildPharmacistActualsTemplate(), 'PharmaPulse_Pharmacist_Actuals_Import_Template.xlsx')
}
