// ============================================================
// Template Version Guard (DX-8, Template System Hardening)
//
// Smallest maintainable versioning model: every template generated by
// templateGenerator.ts carries a single Template Version string on a
// visible Metadata sheet. A workbook with no Metadata sheet at all
// predates DX-8 and is treated as a supported legacy version (every
// import flow before this bundle worked exactly this way) — never
// rejected. A workbook whose Metadata sheet names an explicit version
// NOT in SUPPORTED_TEMPLATE_VERSIONS is rejected with a clear reason
// before any row parsing happens, never a crash or silent mismatch.
// ============================================================

import { TEMPLATE_VERSION } from './templateGenerator'

/** Every template version this build can still import. Grows over
 *  time as new versions ship; old supported versions are removed
 *  only when a real breaking change makes them genuinely unreadable —
 *  not on every release. */
export const SUPPORTED_TEMPLATE_VERSIONS: string[] = [TEMPLATE_VERSION]

export interface TemplateVersionCheckResult {
  supported: boolean
  /** null = legacy file, no Metadata sheet at all (pre-DX-8) — still supported. */
  version: string | null
  reason?: string
}

/** Reads the 'Template Version' row from a parsed Metadata sheet
 *  (rows already converted via XLSX.utils.sheet_to_json, the same
 *  shape every other sheet in this codebase is parsed into). */
export function readTemplateVersion(metadataRows: Array<Record<string, unknown>> | undefined): string | null {
  if (!metadataRows || metadataRows.length === 0) return null
  for (const row of metadataRows) {
    if (row.Field === 'Template Version') {
      const value = row.Value
      return value == null ? null : String(value)
    }
  }
  return null
}

/** Pure check — no Firestore, no file I/O. Callers parse the workbook
 *  once and pass the already-extracted Metadata sheet rows (or
 *  undefined if the workbook has no Metadata sheet at all). */
export function checkTemplateVersion(metadataRows: Array<Record<string, unknown>> | undefined): TemplateVersionCheckResult {
  const version = readTemplateVersion(metadataRows)

  if (version == null) {
    // No Metadata sheet, or no Template Version row in it — a legacy,
    // pre-DX-8 file. Still supported: every column/validation rule in
    // every adapter was already designed against exactly this shape.
    return { supported: true, version: null }
  }

  if (SUPPORTED_TEMPLATE_VERSIONS.includes(version)) {
    return { supported: true, version }
  }

  return {
    supported: false,
    version,
    reason: `This file was generated with template version "${version}", which this build does not support. Download a fresh template and re-enter your data.`,
  }
}
